// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_momentuHMM_TMBExports
#include <TMB.hpp>
#include "momentuhmmTMB.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "momentuhmmTMB") {
    return momentuhmmTMB(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
