
#' Example data simulation
#'
#' Generate the file \code{data/example.RData}, used in other functions' examples and unit tests.

exGen <- function()
{
  set.seed(1)

  # simulate data
  nbAnimals <- 2
  nbStates <- 2
  nbCovs <- 2
  mu<-c(15,50)
  sigma<-c(10,20)
  angleMean <- c(0,0)
  kappa <- c(0.7,1.5)
  stepPar <- c(mu,sigma)
  anglePar <- c(angleMean,kappa)
  stepDist <- "gamma"
  angleDist <- "vm"
  zeroInflation <- FALSE
  obsPerAnimal <- c(500,1000)
  beta <- matrix(c(-1.5,-1.5,0.25,-0.25,-0.1,0.1),3,2,byrow=TRUE)

  simPar <- list(nbAnimals=nbAnimals,nbStates=nbStates,angleMean=angleMean,dist=list(step=stepDist,angle=angleDist),zeroInflation=list(step=zeroInflation,angle=FALSE))

  obsData <- simData(nbAnimals=nbAnimals,nbStates=nbStates,dist=list(step=stepDist,angle=angleDist),
                  Par=list(step=stepPar,angle=anglePar),beta=beta,nbCovs=nbCovs,zeroInflation=list(step=zeroInflation),
                  obsPerAnimal=obsPerAnimal,states=TRUE,lambda=2,errorEllipse=list(M=50,m=50,r=0))
  
  tInd <- which(!is.na(obsData$cov1))
  tmpData <- obsData[tInd,]
  data <- prepData(data.frame(ID=tmpData$ID,x=tmpData$mux,y=tmpData$muy,cov1=tmpData$cov1,cov2=tmpData$cov2,states=tmpData$states),coordNames=c("x","y"),covNames=c("cov1","cov2"))

  # estimate model
  mu0 <- c(20,70)
  sigma0 <- c(10,30)
  kappa0 <- c(1,1)
  stepPar0 <- c(mu0,sigma0)
  anglePar0 <- c(-pi/2,pi/2,kappa0)
  formula <- ~cov1+cos(cov2)
  nbCovs <- length(attr(terms(formula), "term.labels"))

  beta0 <- matrix(c(rep(-1.5,nbStates*(nbStates-1)),rep(0,nbStates*(nbStates-1)*nbCovs)),
                  nrow=nbCovs+1,byrow=TRUE)
  delta0 <- rep(1,nbStates)/nbStates

  par0 <- list(Par=list(step=stepPar0,angle=anglePar0),formula=formula,nbCovs=nbCovs,beta0=beta0,
               delta0=delta0)

  m <- fitHMM(data=data,nbStates=nbStates,Par0=list(step=stepPar0,angle=anglePar0),beta0=beta0,
                delta0=delta0,formula=formula,dist=list(step=stepDist,angle=angleDist),estAngleMean=list(angle=TRUE))

  example <- list(data=data,m=m,simPar=simPar,par0=par0)
  
  inits <- list(a=c(0,0,0,0),P = diag(c(5000 ^ 2,10 * 3600 ^ 2, 5000 ^ 2, 10 * 3600 ^ 2)))
  err.model <- list(x= ~ ln.sd.x - 1, y =  ~ ln.sd.y - 1, rho =  ~ error.corr)
  
  crwOut <- crawlWrap(obsData,ncores=1,theta=c(4,0),fixPar=c(1,1,NA,NA),
   initial.state=inits,
   err.model=err.model)
  
  bestFit<-MIfitHMM(crwOut,nSims=1,ncores=1,nbStates=nbStates,Par0=list(step=stepPar0,angle=anglePar0),beta0=beta0,
                    delta0=delta0,formula=formula,dist=list(step=stepDist,angle=angleDist),estAngleMean=list(angle=TRUE),
                    covNames=c("cov1","cov2"))
  
  bPar<-getPar(bestFit)
  
  miFits<-MIfitHMM(crwOut,nSims=5,ncores=1,nbStates=nbStates,Par0=bPar$Par,beta0=bPar$beta,
                    delta0=bPar$delta,formula=formula,dist=list(step=stepDist,angle=angleDist),estAngleMean=list(angle=TRUE),
                    covNames=c("cov1","cov2"),parIS = 0, fullPost = FALSE)
  
  miExample <- list(obsData=obsData,inits=inits,err.model=err.model,crwData=crwOut,bestFit=bestFit,miHMM=miFits)
  save(example,miExample,file="data/example.RData")
}

# Roxygen documentation for the data file "data/example.RData"

#' Example dataset
#'
#' This data is generated by the function \code{\link{exGen}}, and used in the examples and tests of
#' other functions to keep them as short as possible.
#'
#' It is a list of the following objects:
#' \itemize{
#' \item \code{data} A \code{\link{momentuHMMData}} object
#' \item \code{m} A \code{\link{momentuHMM}} object
#' \item \code{simPar} The parameters used to simulate \code{data}
#' \item \code{par0} The initial parameters in the optimization to fit \code{m}
#' }
#'
#' @name example
#' @usage example
#' @docType data
NULL
