momentuHMMdists<-c('gamma','weibull','exp','lnorm','beta','pois','wrpcauchy','vm')
angledists<-c('wrpcauchy','vm')
stepdists<-c('gamma','weibull','exp','lnorm')
singleParmdists<-c('exp','pois')
nonnegativedists<-c('gamma','weibull','exp','lnorm','pois')
zeroInflationdists<-c('gamma','weibull','exp','lnorm','beta')